### ISSUE TITLE
Issues with datasets

### ISSUE THREAD

**Issue by jacktwosense** [NyleSiddiqui/Minecraft-Mouse-Dynamics-Dataset#1]
Hi,

I've found two issues with the data that I'd love help with:

1) The raw data for both papers have a Button column with categorical values, but there's no way to map these to their event types such as Left/Right/Middle click/drag/scroll.

2) The raw data for the older of the two papers which has 10 users has timestamps rounded to the second. From the engineered features as well as a screenshot of example data in the paper it's clear that the original resolution of the raw data is at least milliseconds if not nanoseconds. Having the raw data for this paper with the original timestamp resolution would be great since the second resolution otherwise makes the raw data unusable.

**Comment by NyleSiddiqui** [comment]
Hi Jack,

Thanks for your interest in the dataset, it was collected for my undergraduate thesis so it's cool to see that someone besides myself and my former colleagues is even aware of its existence haha. 

To address your first point, here is the mapping of categorical values seen in the excel sheet to mouse buttons:
-1 -> mouse movement
0 -> left click (press)
1 -> middle click (press)
2 -> right click (press)
3 -> scroll down
4 -> scroll up
5 -> left click (release)
6 -> right click (release)
7 -> middle click (release)

To address your second point, I see that some of the raw data does have integer timestamp values. Unfortunately I do not have the time to fix this, however I will share the dropbox link that has all of my preprocessing source code upon request if this is an impassable problem for anyone using this dataset.

Your comment made me download the zip files and I actually found that the extracted info for the 40 subject dataset was missing information, so I plan on fixing that soon in case you actually plan on using this dataset.

**Comment by jacktwosense** [comment]
Hi Nyle,

Thank you for the mapping.

Regarding any update to correct missing data in the 40 subject dataset, I'm
not seeing any new commits on github.

If you think the original code would be useful, I'd appreciate access to
it. Otherwise I'll see whether I can use the processed data to reconstruct
the original timestamps.

Best,
Jack
